version: 1.0.{build}
skip_tags: true
image: Visual Studio 2017
configuration: Release
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
artifacts:
- path: S3Download\bin\$(configuration)
  name: S3Download
deploy:
- provider: GitHub
  auth_token:
    secure: KmYWY9jz5FpXpKkxpQvthnDkZiMCi0tmh5PCs/83mu4vm0QsEThuEqhEgMViCbCJ  
